#!/bin/bash
while sleep 10; do
        #s3cmd sync "s3://${AWS_S3_BUCKET}/tests/" ./problems/ --access_key=${AWS_ACCESS_KEY_ID} --secret_key=${AWS_SECRET_ACCESS_KEY} --host=${AWS_S3_HOST} --host-bucket=%\(bucket\)s.${AWS_S3_HOST} --delete-removed;
        s3cmd sync ./problems/ "s3://${AWS_S3_BUCKET}/tests/" --access_key=${AWS_ACCESS_KEY_ID} --secret_key=${AWS_SECRET_ACCESS_KEY} --host=${AWS_S3_HOST} --host-bucket=%\(bucket\)s.${AWS_S3_HOST} --delete-removed --force;
done
